/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface AnythingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingAnythingDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingAnythingGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingAnythingPatch(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingAnythingPost(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingAnythingPut(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingPatch(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingPost(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns anything passed in request data.
     * 
*/
    anythingPut(extraHttpRequestParams?: any): Observable<{}>;

}
