/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface CookiesDeleteGetRequestParams {
    freeform?: any;
}

export interface CookiesSetGetRequestParams {
    freeform?: any;
}

export interface CookiesSetNameValueGetRequestParams {
    name: string;
    value: string;
}


export interface CookiesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Deletes cookie(s) as provided by the query string and redirects to cookie list.
     * 
* @param requestParameters
     */
    cookiesDeleteGet(requestParameters: CookiesDeleteGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns cookie data.
     * 
*/
    cookiesGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Sets cookie(s) as provided by the query string and redirects to cookie list.
     * 
* @param requestParameters
     */
    cookiesSetGet(requestParameters: CookiesSetGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Sets a cookie and redirects to cookie list.
     * 
* @param requestParameters
     */
    cookiesSetNameValueGet(requestParameters: CookiesSetNameValueGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
