/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface ImagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns a simple image of the type suggest by the Accept header.
     * 
*/
    imageGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple JPEG image.
     * 
*/
    imageJpegGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple PNG image.
     * 
*/
    imagePngGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple SVG image.
     * 
*/
    imageSvgGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple WEBP image.
     * 
*/
    imageWebpGet(extraHttpRequestParams?: any): Observable<{}>;

}
