/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface AbsoluteRedirectNGetRequestParams {
    n: any;
}

export interface RedirectNGetRequestParams {
    n: any;
}

export interface RedirectToGetRequestParams {
    url: string;
    statusCode?: any;
}

export interface RedirectToPostRequestParams {
    url: string;
    statusCode?: any | null;
}

export interface RedirectToPutRequestParams {
    url: string;
    statusCode?: any | null;
}

export interface RelativeRedirectNGetRequestParams {
    n: any;
}


export interface RedirectsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Absolutely 302 Redirects n times.
     * 
* @param requestParameters
     */
    absoluteRedirectNGet(requestParameters: AbsoluteRedirectNGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302 Redirects n times.
     * 
* @param requestParameters
     */
    redirectNGet(requestParameters: RedirectNGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302/3XX Redirects to the given URL.
     * 
*/
    redirectToDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302/3XX Redirects to the given URL.
     * 
* @param requestParameters
     */
    redirectToGet(requestParameters: RedirectToGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302/3XX Redirects to the given URL.
     * 
*/
    redirectToPatch(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302/3XX Redirects to the given URL.
     * 
* @param requestParameters
     */
    redirectToPost(requestParameters: RedirectToPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 302/3XX Redirects to the given URL.
     * 
* @param requestParameters
     */
    redirectToPut(requestParameters: RedirectToPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Relatively 302 Redirects n times.
     * 
* @param requestParameters
     */
    relativeRedirectNGet(requestParameters: RelativeRedirectNGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
