/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface RequestInspectionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Return the incoming request\&#39;s HTTP headers.
     * 
*/
    headersGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns the requester\&#39;s IP Address.
     * 
*/
    ipGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Return the incoming requests\&#39;s User-Agent header.
     * 
*/
    userAgentGet(extraHttpRequestParams?: any): Observable<{}>;

}
