/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface ResponseFormatsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns Brotli-encoded data.
     * 
*/
    brotliGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns Deflate-encoded data.
     * 
*/
    deflateGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns page denied by robots.txt rules.
     * 
*/
    denyGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a UTF-8 encoded body.
     * 
*/
    encodingUtf8Get(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns GZip-encoded data.
     * 
*/
    gzipGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple HTML document.
     * 
*/
    htmlGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple JSON document.
     * 
*/
    jsonGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns some robots.txt rules.
     * 
*/
    robotsTxtGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Returns a simple XML document.
     * 
*/
    xmlGet(extraHttpRequestParams?: any): Observable<{}>;

}
