/**
 * httpbin.org
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: me@kennethreitz.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';


export interface StatusCodesDeleteRequestParams {
    codes: any;
}

export interface StatusCodesGetRequestParams {
    codes: any;
}

export interface StatusCodesPatchRequestParams {
    codes: any;
}

export interface StatusCodesPostRequestParams {
    codes: any;
}

export interface StatusCodesPutRequestParams {
    codes: any;
}


export interface StatusCodesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Return status code or random status code if more than one are given
     * 
* @param requestParameters
     */
    statusCodesDelete(requestParameters: StatusCodesDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Return status code or random status code if more than one are given
     * 
* @param requestParameters
     */
    statusCodesGet(requestParameters: StatusCodesGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Return status code or random status code if more than one are given
     * 
* @param requestParameters
     */
    statusCodesPatch(requestParameters: StatusCodesPatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Return status code or random status code if more than one are given
     * 
* @param requestParameters
     */
    statusCodesPost(requestParameters: StatusCodesPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Return status code or random status code if more than one are given
     * 
* @param requestParameters
     */
    statusCodesPut(requestParameters: StatusCodesPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
